# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\src\templates\allAccountsPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_allAccounts(object):
    def setupUi(self, allAccounts):
        allAccounts.setObjectName("allAccounts")
        allAccounts.resize(1080, 720)
        allAccounts.setMinimumSize(QtCore.QSize(1080, 720))
        allAccounts.setMaximumSize(QtCore.QSize(1080, 720))
        allAccounts.setBaseSize(QtCore.QSize(1080, 720))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        allAccounts.setFont(font)
        allAccounts.setStyleSheet("background-color: rgb(2, 13, 165);")
        self.genPassTab = QtWidgets.QPushButton(allAccounts)
        self.genPassTab.setGeometry(QtCore.QRect(465, 72, 66, 66))
        self.genPassTab.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.genPassTab.setStyleSheet("border-radius: 33;")
        self.genPassTab.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\src\\templates\\../images/gen password on.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.genPassTab.setIcon(icon)
        self.genPassTab.setIconSize(QtCore.QSize(66, 66))
        self.genPassTab.setObjectName("genPassTab")
        self.accountsTab = QtWidgets.QPushButton(allAccounts)
        self.accountsTab.setEnabled(False)
        self.accountsTab.setGeometry(QtCore.QRect(550, 72, 66, 66))
        self.accountsTab.setStyleSheet("border-radius: 33;")
        self.accountsTab.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\src\\templates\\../images/accounts off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.accountsTab.setIcon(icon1)
        self.accountsTab.setIconSize(QtCore.QSize(66, 66))
        self.accountsTab.setObjectName("accountsTab")
        self.accountFrame = QtWidgets.QFrame(allAccounts)
        self.accountFrame.setGeometry(QtCore.QRect(180, 142, 720, 480))
        self.accountFrame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 25;")
        self.accountFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.accountFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.accountFrame.setObjectName("accountFrame")
        self.searchBox = QtWidgets.QLineEdit(self.accountFrame)
        self.searchBox.setEnabled(True)
        self.searchBox.setGeometry(QtCore.QRect(210, 20, 296, 32))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(14)
        self.searchBox.setFont(font)
        self.searchBox.setStyleSheet("border-color: rgb(204, 204, 204);\n"
"border: .5 solid;")
        self.searchBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.searchBox.setObjectName("searchBox")
        self.searchIcon = QtWidgets.QLabel(self.accountFrame)
        self.searchIcon.setEnabled(False)
        self.searchIcon.setGeometry(QtCore.QRect(480, 30, 12, 13))
        self.searchIcon.setText("")
        self.searchIcon.setPixmap(QtGui.QPixmap(".\\src\\templates\\../images/search icon.png"))
        self.searchIcon.setObjectName("searchIcon")
        self.addAccountBtn = QtWidgets.QPushButton(self.accountFrame)
        self.addAccountBtn.setGeometry(QtCore.QRect(570, 20, 48, 39))
        self.addAccountBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addAccountBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\src\\templates\\../images/add account icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addAccountBtn.setIcon(icon2)
        self.addAccountBtn.setIconSize(QtCore.QSize(48, 39))
        self.addAccountBtn.setObjectName("addAccountBtn")
        self.importBtn = QtWidgets.QPushButton(allAccounts)
        self.importBtn.setGeometry(QtCore.QRect(52, 651, 120, 32))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(14)
        self.importBtn.setFont(font)
        self.importBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.importBtn.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.importBtn.setObjectName("importBtn")
        self.exportBtn = QtWidgets.QPushButton(allAccounts)
        self.exportBtn.setGeometry(QtCore.QRect(900, 651, 120, 32))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(14)
        self.exportBtn.setFont(font)
        self.exportBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exportBtn.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.exportBtn.setObjectName("exportBtn")

        self.retranslateUi(allAccounts)
        QtCore.QMetaObject.connectSlotsByName(allAccounts)

    def retranslateUi(self, allAccounts):
        _translate = QtCore.QCoreApplication.translate
        allAccounts.setWindowTitle(_translate("allAccounts", "View All Accounts"))
        self.searchBox.setPlaceholderText(_translate("allAccounts", "Search for account"))
        self.importBtn.setText(_translate("allAccounts", "Import"))
        self.exportBtn.setText(_translate("allAccounts", "Export"))
