# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\src\templates\changePassPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_changePass(object):
    def setupUi(self, changePass):
        changePass.setObjectName("changePass")
        changePass.resize(1080, 720)
        changePass.setMinimumSize(QtCore.QSize(1080, 720))
        changePass.setMaximumSize(QtCore.QSize(1080, 720))
        changePass.setStyleSheet("background-color: rgb(2, 13, 165);")
        self.changePassContainer = QtWidgets.QFrame(changePass)
        self.changePassContainer.setGeometry(QtCore.QRect(300, 120, 480, 480))
        self.changePassContainer.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 25;")
        self.changePassContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.changePassContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.changePassContainer.setObjectName("changePassContainer")
        self.pageTitle = QtWidgets.QLabel(self.changePassContainer)
        self.pageTitle.setGeometry(QtCore.QRect(20, 30, 441, 71))
        self.pageTitle.setStyleSheet("color: rgb(2, 13, 165);\n"
"font: 40pt \"Open Sans\";")
        self.pageTitle.setObjectName("pageTitle")
        self.nameOfAccountLbl = QtWidgets.QLabel(self.changePassContainer)
        self.nameOfAccountLbl.setGeometry(QtCore.QRect(60, 120, 171, 31))
        self.nameOfAccountLbl.setStyleSheet("font: 16pt \"Open Sans\";")
        self.nameOfAccountLbl.setObjectName("nameOfAccountLbl")
        self.usernameLbl = QtWidgets.QLabel(self.changePassContainer)
        self.usernameLbl.setGeometry(QtCore.QRect(60, 180, 171, 21))
        self.usernameLbl.setStyleSheet("font: 16pt \"Open Sans\";\n"
"")
        self.usernameLbl.setObjectName("usernameLbl")
        self.passwordEdit = QtWidgets.QLineEdit(self.changePassContainer)
        self.passwordEdit.setGeometry(QtCore.QRect(60, 230, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(16)
        self.passwordEdit.setFont(font)
        self.passwordEdit.setStyleSheet("border: 1 solid grey;")
        self.passwordEdit.setText("")
        self.passwordEdit.setObjectName("passwordEdit")
        self.confirmPassEdit = QtWidgets.QLineEdit(self.changePassContainer)
        self.confirmPassEdit.setGeometry(QtCore.QRect(60, 300, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(16)
        self.confirmPassEdit.setFont(font)
        self.confirmPassEdit.setStyleSheet("border: 1 solid grey;")
        self.confirmPassEdit.setObjectName("confirmPassEdit")
        self.cancelBtn = QtWidgets.QPushButton(self.changePassContainer)
        self.cancelBtn.setGeometry(QtCore.QRect(30, 380, 101, 41))
        self.cancelBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancelBtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 0, 0);\n"
"font: 20pt \"Open Sans\";\n"
"")
        self.cancelBtn.setObjectName("cancelBtn")
        self.changePassBtn = QtWidgets.QPushButton(self.changePassContainer)
        self.changePassBtn.setGeometry(QtCore.QRect(220, 380, 241, 41))
        self.changePassBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.changePassBtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(2, 165, 7);\n"
"font: 20pt \"Open Sans\";")
        self.changePassBtn.setObjectName("changePassBtn")

        self.retranslateUi(changePass)
        QtCore.QMetaObject.connectSlotsByName(changePass)

    def retranslateUi(self, changePass):
        _translate = QtCore.QCoreApplication.translate
        changePass.setWindowTitle(_translate("changePass", "Change Password"))
        self.pageTitle.setText(_translate("changePass", "Change Password"))
        self.nameOfAccountLbl.setText(_translate("changePass", "Name of account"))
        self.usernameLbl.setText(_translate("changePass", "Username"))
        self.passwordEdit.setPlaceholderText(_translate("changePass", "Enter new password"))
        self.confirmPassEdit.setPlaceholderText(_translate("changePass", "Confirm new password"))
        self.cancelBtn.setText(_translate("changePass", "Cancel"))
        self.changePassBtn.setText(_translate("changePass", "Change Password"))
