# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\src\templates\exportAccountsPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_exportPage(object):
    def setupUi(self, exportPage):
        exportPage.setObjectName("exportPage")
        exportPage.resize(1080, 720)
        exportPage.setMinimumSize(QtCore.QSize(1080, 720))
        exportPage.setMaximumSize(QtCore.QSize(1080, 720))
        exportPage.setStyleSheet("background-color: rgb(2, 13, 165);")
        self.exportContainer = QtWidgets.QFrame(exportPage)
        self.exportContainer.setGeometry(QtCore.QRect(300, 120, 480, 480))
        self.exportContainer.setStyleSheet("border-radius: 25;\n"
"background-color: rgb(255, 255, 255);")
        self.exportContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.exportContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.exportContainer.setObjectName("exportContainer")
        self.titleLbl = QtWidgets.QLabel(self.exportContainer)
        self.titleLbl.setGeometry(QtCore.QRect(50, 50, 391, 71))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(32)
        self.titleLbl.setFont(font)
        self.titleLbl.setStyleSheet("color: rgb(2, 13, 165);")
        self.titleLbl.setObjectName("titleLbl")
        self.csvBtn = QtWidgets.QPushButton(self.exportContainer)
        self.csvBtn.setGeometry(QtCore.QRect(60, 180, 127, 37))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(20)
        self.csvBtn.setFont(font)
        self.csvBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.csvBtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(2, 165, 7);")
        self.csvBtn.setObjectName("csvBtn")
        self.jsonBtn = QtWidgets.QPushButton(self.exportContainer)
        self.jsonBtn.setGeometry(QtCore.QRect(300, 180, 127, 37))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(20)
        self.jsonBtn.setFont(font)
        self.jsonBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.jsonBtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(2, 165, 7);")
        self.jsonBtn.setObjectName("jsonBtn")
        self.disclaimer = QtWidgets.QLabel(self.exportContainer)
        self.disclaimer.setGeometry(QtCore.QRect(20, 270, 451, 20))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(14)
        self.disclaimer.setFont(font)
        self.disclaimer.setStyleSheet("color: rgba(2, 13, 165, 128);")
        self.disclaimer.setObjectName("disclaimer")
        self.cancelBtn = QtWidgets.QPushButton(self.exportContainer)
        self.cancelBtn.setGeometry(QtCore.QRect(180, 350, 127, 37))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(20)
        self.cancelBtn.setFont(font)
        self.cancelBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancelBtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 0, 0);")
        self.cancelBtn.setObjectName("cancelBtn")

        self.retranslateUi(exportPage)
        QtCore.QMetaObject.connectSlotsByName(exportPage)

    def retranslateUi(self, exportPage):
        _translate = QtCore.QCoreApplication.translate
        exportPage.setWindowTitle(_translate("exportPage", "Export Accounts"))
        self.titleLbl.setText(_translate("exportPage", "Export Accounts as"))
        self.csvBtn.setText(_translate("exportPage", "CSV"))
        self.jsonBtn.setText(_translate("exportPage", "JSON"))
        self.disclaimer.setText(_translate("exportPage", "File can be found on the Desktop under Accounts"))
        self.cancelBtn.setText(_translate("exportPage", "Cancel"))
