# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\src\templates\viewAccountPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_viewAccount(object):
    def setupUi(self, viewAccount):
        viewAccount.setObjectName("viewAccount")
        viewAccount.resize(1080, 720)
        viewAccount.setMinimumSize(QtCore.QSize(1080, 720))
        viewAccount.setMaximumSize(QtCore.QSize(1080, 720))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        viewAccount.setFont(font)
        viewAccount.setStyleSheet("background-color: rgb(2, 13, 165);")
        self.accountContainer = QtWidgets.QFrame(viewAccount)
        self.accountContainer.setGeometry(QtCore.QRect(300, 120, 480, 480))
        self.accountContainer.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:25;")
        self.accountContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.accountContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.accountContainer.setObjectName("accountContainer")
        self.viewAccountTitle = QtWidgets.QLabel(self.accountContainer)
        self.viewAccountTitle.setGeometry(QtCore.QRect(80, 80, 331, 51))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(40)
        self.viewAccountTitle.setFont(font)
        self.viewAccountTitle.setStyleSheet("color: rgb(2, 13, 165);")
        self.viewAccountTitle.setObjectName("viewAccountTitle")
        self.nameOfAccountLbl = QtWidgets.QLabel(self.accountContainer)
        self.nameOfAccountLbl.setGeometry(QtCore.QRect(110, 150, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(16)
        self.nameOfAccountLbl.setFont(font)
        self.nameOfAccountLbl.setText("")
        self.nameOfAccountLbl.setObjectName("nameOfAccountLbl")
        self.usernameLbl = QtWidgets.QLabel(self.accountContainer)
        self.usernameLbl.setGeometry(QtCore.QRect(110, 210, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(16)
        self.usernameLbl.setFont(font)
        self.usernameLbl.setText("")
        self.usernameLbl.setObjectName("usernameLbl")
        self.passwordLbl = QtWidgets.QLabel(self.accountContainer)
        self.passwordLbl.setGeometry(QtCore.QRect(110, 270, 311, 21))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(16)
        self.passwordLbl.setFont(font)
        self.passwordLbl.setText("")
        self.passwordLbl.setObjectName("passwordLbl")
        self.changePassBtn = QtWidgets.QPushButton(self.accountContainer)
        self.changePassBtn.setGeometry(QtCore.QRect(110, 340, 251, 38))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(20)
        self.changePassBtn.setFont(font)
        self.changePassBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.changePassBtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(2, 13, 165);")
        self.changePassBtn.setObjectName("changePassBtn")
        self.deleteBtn = QtWidgets.QPushButton(self.accountContainer)
        self.deleteBtn.setGeometry(QtCore.QRect(170, 410, 130, 38))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(20)
        self.deleteBtn.setFont(font)
        self.deleteBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.deleteBtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 0, 0);")
        self.deleteBtn.setObjectName("deleteBtn")
        self.backBtn = QtWidgets.QPushButton(self.accountContainer)
        self.backBtn.setGeometry(QtCore.QRect(30, 20, 120, 35))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(20)
        self.backBtn.setFont(font)
        self.backBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backBtn.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"")
        self.backBtn.setObjectName("backBtn")
        self.copyUserBtn = QtWidgets.QPushButton(self.accountContainer)
        self.copyUserBtn.setGeometry(QtCore.QRect(70, 210, 25, 30))
        self.copyUserBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.copyUserBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\src\\templates\\../images/copy icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.copyUserBtn.setIcon(icon)
        self.copyUserBtn.setIconSize(QtCore.QSize(25, 30))
        self.copyUserBtn.setObjectName("copyUserBtn")
        self.copyPassBtn = QtWidgets.QPushButton(self.accountContainer)
        self.copyPassBtn.setGeometry(QtCore.QRect(70, 270, 25, 30))
        self.copyPassBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.copyPassBtn.setText("")
        self.copyPassBtn.setIcon(icon)
        self.copyPassBtn.setIconSize(QtCore.QSize(25, 30))
        self.copyPassBtn.setObjectName("copyPassBtn")

        self.retranslateUi(viewAccount)
        QtCore.QMetaObject.connectSlotsByName(viewAccount)

    def retranslateUi(self, viewAccount):
        _translate = QtCore.QCoreApplication.translate
        viewAccount.setWindowTitle(_translate("viewAccount", "View Account"))
        self.viewAccountTitle.setText(_translate("viewAccount", "View Account"))
        self.changePassBtn.setText(_translate("viewAccount", "Change Password"))
        self.deleteBtn.setText(_translate("viewAccount", "Delete"))
        self.backBtn.setText(_translate("viewAccount", "Back"))
